name: deployment

on:
  push:
    branches: [main]

jobs:
  cleanup:
    name: 'Prepare server for deployment'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: clean up data
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: adu-nasib
          password: ${{ secrets.ROOT_PASSWORD }}
          script: |
            rm -rf ~/adu-nasib-api/release.zip

  build:
    name: 'Build backend assets'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: build backend assets
        run: npm install && npm run build

      - name: compress artifact
        run: zip release.zip ./dist -r

      - name: upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: adu-nasib
          password: ${{ secrets.ROOT_PASSWORD }}
          source: ./release.zip
          target: '~/adu-nasib-api'

  deploy:
    name: 'Deploy to Productions'
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: adu-nasib
          password: ${{ secrets.ROOT_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            node --version
            pwd
            pm2 stop api && pm2 reset api
            cd adu-nasib-api && git fetch && git reset --hard origin/main
            [ -d ~/adu-nasib-api/dist/public ] && echo copying ~/adu-nasib-api/dist/public ..." && mv ~/adu-nasib-api/dist/public ~/adu-nasib-api/public
            rm -rf ~/adu-nasib-api/dist && echo "dist directory removed."
            npm install
            npm run migrate
            unzip -o ~/adu-nasib-api/release.zip -d ~/adu-nasib-api
            [ -d ~/adu-nasib-api/public ] && echo "restoring ~/adu-nasib-api/public ..." && mv ~/adu-nasib-api/public ~/adu-nasib-api/dist/public
            cd ~
            pm2 start api
